import { useState, useRef, useEffect, useCallback } from 'react'
import { useChatStore } from '../stores/useChatStore'
import { useAgentStore } from '../stores/useAgentStore'
import { useTripStore } from '../stores/useTripStore'
import { useMapStore } from '../stores/useMapStore'
import { agentLoop } from '../engine/agent/AgentLoop'
import AgentStatusBar from '../components/agent/AgentStatusBar'
import ChatBubble from '../components/assistant/ChatBubble'
import QuickActions from '../components/assistant/QuickActions'
import VoiceInputButton from '../components/assistant/VoiceInputButton'
import ToolCallBubble from '../components/assistant/ToolCallBubble'

export default function AssistantPage() {
  const [input, setInput] = useState('')
  const messages = useChatStore((s) => s.messages)
  const isProcessing = useChatStore((s) => s.isProcessing)
  const sendMessage = useChatStore((s) => s.sendMessage)
  const addMessage = useChatStore((s) => s.addMessage)
  const setProcessing = useChatStore((s) => s.setProcessing)
  const activeToolCalls = useAgentStore((s) => s.activeToolCalls)
  const phase = useAgentStore((s) => s.phase)
  const setPhase = useAgentStore((s) => s.setPhase)
  const fitBounds = useTripStore((s) => s.setTrip)
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, activeToolCalls])

  const handleSend = useCallback(async () => {
    const text = input.trim()
    if (!text || isProcessing) return
    setInput('')
    sendMessage(text)

    try {
      const response = await agentLoop.run(text)

      // Check if trip was generated by the agent and fit map bounds
      const trip = useTripStore.getState().currentTrip
      if (trip) {
        const allNodes = trip.days.flatMap((d) => [
          ...d.segments.morning,
          ...d.segments.afternoon,
          ...d.segments.evening,
        ])
        if (allNodes.length > 0) {
          useMapStore.getState().fitBounds(allNodes.map((n) => ({ lat: n.lat, lng: n.lng })))
        }
      }

      // Show tool calls in chat if any were made
      const toolCalls = useAgentStore.getState().activeToolCalls
      if (toolCalls.length > 0) {
        addMessage({
          role: 'assistant',
          content: response,
          type: 'tool_call',
          toolCalls: toolCalls.map((tc) => ({
            name: tc.name,
            args: {},
            result: tc.result,
          })),
        })
      } else {
        addMessage({ role: 'assistant', content: response, type: 'text' })
      }
    } catch (err) {
      console.error('[AssistantPage] handleSend error:', err)
      addMessage({
        role: 'assistant',
        content: '抱歉，处理请求出错：' + (err instanceof Error ? err.message : '未知错误'),
        type: 'text',
      })
    } finally {
      setProcessing(false)
    }
  }, [input, sendMessage, addMessage, setProcessing])

  // Don't depend on isProcessing to avoid stale closure issues
  const canSend = !isProcessing && input.trim()

  const handleQuickAction = (text: string) => {
    setInput(text)
    // Trigger send immediately for quick actions
    setTimeout(() => {
      if (text.trim()) {
        sendMessage(text)
        setProcessing(true)
        agentLoop.run(text).then((response) => {
          const trip = useTripStore.getState().currentTrip
          if (trip) {
            const allNodes = trip.days.flatMap((d) => [
              ...d.segments.morning,
              ...d.segments.afternoon,
              ...d.segments.evening,
            ])
            if (allNodes.length > 0) {
              useMapStore.getState().fitBounds(allNodes.map((n) => ({ lat: n.lat, lng: n.lng })))
            }
          }
          const toolCalls = useAgentStore.getState().activeToolCalls
          if (toolCalls.length > 0) {
            addMessage({
              role: 'assistant',
              content: response,
              type: 'tool_call',
              toolCalls: toolCalls.map((tc) => ({ name: tc.name, args: {}, result: tc.result })),
            })
          } else {
            addMessage({ role: 'assistant', content: response, type: 'text' })
          }
          setProcessing(false)
        }).catch(() => {
          addMessage({ role: 'assistant', content: '抱歉，处理您的请求时出错了。', type: 'text' })
          setProcessing(false)
        })
      }
    }, 100)
  }

  const handleVoiceResult = (text: string) => {
    setInput(text)
    setTimeout(() => {
      if (text.trim()) {
        handleSend()
      }
    }, 300)
  }

  return (
    <div className="flex flex-col h-full">
      <AgentStatusBar />

      {/* Chat messages */}
      <div className="flex-1 overflow-y-auto px-3 py-2 space-y-2 no-scrollbar">
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center h-full text-center">
            <div className="text-5xl mb-3">🤖</div>
            <p className="text-sm font-bold text-text-primary">童行助手就绪</p>
            <p className="text-xs text-text-muted mt-1">
              用自然语言告诉我您的出行计划<br />我将为您规划一切
            </p>
          </div>
        )}

        {messages.map((msg) =>
          msg.type === 'tool_call' && msg.toolCalls ? (
            <ToolCallBubble key={msg.id} message={msg} toolCalls={msg.toolCalls} />
          ) : (
            <ChatBubble key={msg.id} message={msg} />
          )
        )}

        {/* Loading / processing indicator */}
        {isProcessing && (
          <div className="flex items-start gap-2">
            <div className="w-8 h-8 rounded-full bg-sky-blue/20 flex items-center justify-center text-sm flex-shrink-0">
              🤖
            </div>
            <div className="bg-white rounded-2xl rounded-tl-sm px-4 py-3 shadow-sm max-w-[75%]">
              <div className="flex items-center gap-1">
                <span className="w-2 h-2 rounded-full bg-warm-yellow animate-bounce" style={{ animationDelay: '0ms' }} />
                <span className="w-2 h-2 rounded-full bg-warm-yellow animate-bounce" style={{ animationDelay: '150ms' }} />
                <span className="w-2 h-2 rounded-full bg-warm-yellow animate-bounce" style={{ animationDelay: '300ms' }} />
              </div>
            </div>
          </div>
        )}

        {/* Active tool calls indicator */}
        {activeToolCalls.length > 0 && (
          <div className="flex items-center gap-2 px-3 py-2 bg-warm-yellow/5 rounded-xl border border-warm-yellow/20">
            <span className="animate-pulse-soft text-sm">⚙️</span>
            <span className="text-xs text-text-secondary">
              {activeToolCalls.map((tc) => tc.name).join(', ')} 执行中...
            </span>
          </div>
        )}

        <div ref={bottomRef} />
      </div>

      {/* Quick actions */}
      <QuickActions onSelect={handleQuickAction} />

      {/* Input area */}
      <div className="px-3 py-2 bg-white border-t border-gray-100 safe-area-bottom">
        <div className="flex items-center gap-2">
          <VoiceInputButton onResult={handleVoiceResult} />
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="输入出行需求..."
            className="flex-1 h-10 px-3 text-sm bg-gray-50 rounded-xl border-none outline-none text-text-primary placeholder:text-gray-300"
          />
          <button
            onClick={handleSend}
            disabled={!canSend}
            className="w-10 h-10 flex items-center justify-center bg-warm-yellow text-white rounded-xl disabled:opacity-40 active:scale-95 transition-all"
          >
            <span className="text-lg">➤</span>
          </button>
        </div>
      </div>
    </div>
  )
}
